[package]
name = "wasix"
version = "0.12.15"
authors = ["The Cranelift Project Developers", "john-sharratt"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
description = "WASIX API bindings for Rust"
edition = "2018"
categories = ["no-std", "wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/wasix-org/wasix-abi-rust"
readme = "README.md"
documentation = "https://docs.rs/wasix"

[dependencies]
# When built as part of libstd
compiler_builtins = { version = "0.1", optional = true }
core = { version = "1.0", optional = true, package = "rustc-std-workspace-core" }
rustc-std-workspace-alloc = { version = "1.0", optional = true }
wasi = { version = "0.11.0", default-features = false }

[features]
default = ["std"]
std = [ "wasi/std" ]
# Unstable feature to support being a libstd dependency
rustc-dep-of-std = ["compiler_builtins", "core", "rustc-std-workspace-alloc", "wasi/rustc-dep-of-std"]

[badges]
maintenance = { status = "experimental" }
